binaries:
  stage: build
  image: golang:$GO_VERSION-alpine
  extends:
  - .rules:merge_request_or_release
  - .go-cache
  script:
  - apk add -U git make
  - make all
  artifacts:
    paths:
    - out/nesting-*
  parallel:
    matrix:
    - OS_ARCHS:
      - linux/amd64
  needs: []

binaries darwin/arm64:
  stage: build
  tags:
  - saas-macos-medium-m1
  extends:
  - .rules:merge_request_or_release
  - .go-cache
  variables:
    OS_ARCHS: darwin/arm64
  script:
  - asdf plugin-add golang https://github.com/kennyp/asdf-golang.git
  - asdf install golang $GO_VERSION
  - make all
  - codesign --entitlements vz.entitlements -s - out/nesting-darwin-arm64
  artifacts:
    paths:
    - out/nesting-*
  needs: []
