default:
  tags:
    - gitlab-org

variables:
  GO_VERSION: 1.21.6
  OUT_PATH: out
  PACKAGE_REGISTRY_URL: "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/generic/releases"

.go-cache:
  variables:
    GOCACHE: $CI_PROJECT_DIR/.gocache
  before_script:
  - mkdir -p "${GOCACHE}"
  - GOCACHE=$(realpath $GOCACHE)
  cache:
    paths:
    - .gocache/
    key: "${CI_JOB_NAME_SLUG}"

