include:
- template: Jobs/SAST.latest.gitlab-ci.yml
- template: Jobs/Dependency-Scanning.latest.gitlab-ci.yml
- template: Jobs/Secret-Detection.latest.gitlab-ci.yml

test:
  stage: test
  image: golang:$GO_VERSION-alpine
  extends:
  - .rules:merge_request_or_release
  - .go-cache
  script:
  - apk add -U make
  - make test

test-race:
  stage: test
  # `-race` flag for `go test` requires that CGO_ENABLED=1 is set and that a proper
  # gcc toolchain is prepared. Basing on our experience from gitlab-runner repo, it'secrets:
  # just easier to switch to a debian-based Go image for this kind of test jobs. While
  # we keep the rest of jobs using the alpine-based images to make them slightly faster.
  image: golang:$GO_VERSION-bullseye
  extends:
  - .rules:merge_request_or_release
  - .go-cache
  script:
  - make test-race

shell check:
  image: koalaman/shellcheck-alpine:stable
  stage: test
  extends:
  - .rules:merge_request_or_release
  before_script:
  - shellcheck --version
  - apk add make
  script:
  - make shellcheck
