upload-binaries:
  stage: upload
  image: alpine:latest
  extends:
  - .rules:upload
  dependencies:
  - binaries
  - binaries darwin/arm64
  script:
  - apk add curl gnupg make
  - make upload-release
  environment:
    name: upload
  artifacts:
    paths:
    - manifest.txt
